version: "3"
services:
  car-service:
    image: car-service:latest
    build:
      context: ./
    container_name: car-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/car_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
  postgresql:
    image: postgres:15.2-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_service
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 5s
      retries: 10