apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis-consumer
  template:
    metadata:
      labels:
        app: artemis-consumer
    spec:
      containers:
        - name: artemis-consumer
          image: xini/artemis-consumer:2.5
          env:
            - name: SPRING_ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: artemis
                  key: user
            - name: SPRING_ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artemis
                  key: password
          envFrom:
            - configMapRef:
                name: artemis-consumer
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10