apiVersion: v1
kind: ConfigMap
metadata:
  name: car-service-artemis
data:
  CARSERVICE_ARTEMIS_QUEUE: orders
  SPRING_ARTEMIS_BROKERURL: tcp://artemis:61616
  SPRING_ARTEMIS_USER: artemis
  SPRING_ARTEMIS_PASSWORD: artemis