apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
        - name: car-service
          image: xini/car-service:2.4
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: SPRING_ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: artemis
                  key: user
            - name: SPRING_ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artemis
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: artemis
          envFrom:
            - configMapRef:
                name: car-service-common
            - configMapRef:
                name: car-service-apache-kafka
            - configMapRef:
                name: car-service-artemis
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 10