name: main
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Change permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Print current version
        id: version
        run: echo "version=$(./gradlew -q version)" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.version.outputs.version }}
  regular-images:
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module:
          - car-service
          - apache-kafka-consumer
          - artemis-consumer
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          build-args: module=${{ matrix.module }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.module }}:${{ needs.build.outputs.version }}
          push: true
  car-service-native-images:
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        springActiveProfile:
          - apache-kafka
          - artemis
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.native
          build-args: |
            module=car-service
            springActiveProfile=${{ matrix.springActiveProfile }}
          tags: ${{ secrets.DOCKER_USERNAME }}/car-service:${{ needs.build.outputs.version }}-native-${{ matrix.springActiveProfile }}
          push: true
  consumer-native-images:
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        module:
          - apache-kafka-consumer
          - artemis-consumer
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.native
          build-args: |
            module=${{ matrix.module }}
            springActiveProfile=default
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.module }}:${{ needs.build.outputs.version }}-native
          push: true
